# Generated by Django 5.2.6 on 2025-09-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_dailyspecial_delete_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyspecial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
