# Generated by Django 5.2.6 on 2025-09-12 02:27

from django.db import migrations
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_dailyspecial_image_alter_menuitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='dailyspecial',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
